
export const menulist = [
  
  {
    title: "Loans",
    submenu: [
      {
        title: "Personal Loan",
        submenu: [
          { title: "Bank Wise", },
          { title: "Applicant Type" },
          { title: "Monthly Salary Wise" },
          { title: "Salary Mode" },
          { title: "Loan Product" },
          { title: "Loan Program" },
          { title: "Loan Amount Wise" },
          { title: "Loan Tenure Wise" },
          { title: "Cibil Score" },
          { title: "Cibil History" },
          { title: "Age Wise" },
          { title: "Employer Type" },
          { title: "Specific Employer Category" },
          { title: "Specific Degree Wise Funding" },
          { title: "Employee Current Job Experience" },
          { title: "Processing Fee Wise" },
          { title: "Foreclosure Charges" },
          { title: "Insurance (%) Wise" },
          { title: "For Wise" },
          { title: "Pre-Payment Wise" },
          { title: "Part Payment Wise" },
          { title: "Mortorium Wise" },
          { title: "Cibil Enquiry" },
          { title: "Lockin Period Wise" },
          { title: "Loan TAT Wise" },
          { title: "PF or TDS Deduction Mandatory" },
          { title: "Other" },
        ],
      },
      {
        title: "Home Loan",
        submenu: [
          { title: "Bank Wise" },
          { title: "Applicant Type" },
          { title: "Monthly Salary Wise" },
          { title: "Salary Mode" },
          { title: "Loan Product" },
          { title: "Loan Program" },
          { title: "Loan Amount Wise" },
          { title: "Loan Tenure Wise" },
          { title: "Cibil Score" },
          { title: "Cibil History" },
          { title: "Age Wise" },
          { title: "Employer Type" },
          { title: "Specific Employer Category" },
          { title: "Specific Degree Wise Funding" },
          { title: "Employee Current Job Experience" },
          { title: "Processing Fee Wise" },
          { title: "Foreclosure Charges" },
          { title: "Insurance (%) Wise" },
          { title: "For Wise" },
          { title: "Pre-Payment Wise" },
          { title: "Part Payment Wise" },
          { title: "Mortorium Wise" },
          { title: "Cibil Enquiry" },
          { title: "Lockin Period Wise" },
          { title: "Loan TAT Wise" },
          { title: "PF or TDS Deduction Mandatory" },
          { title: "Other" },
        ],
      },
      {
        title: "Loan Against Property",
        submenu: [
          { title: "Bank Wise" },
          { title: "Applicant Type" },
          { title: "Monthly Salary Wise" },
          { title: "Salary Mode" },
          { title: "Loan Product" },
          { title: "Loan Program" },
          { title: "Loan Amount Wise" },
          { title: "Loan Tenure Wise" },
          { title: "Cibil Score" },
          { title: "Cibil History" },
          { title: "Age Wise" },
          { title: "Employer Type" },
          { title: "Specific Employer Category" },
          { title: "Specific Degree Wise Funding" },
          { title: "Employee Current Job Experience" },
          { title: "Processing Fee Wise" },
          { title: "Foreclosure Charges" },
          { title: "Insurance (%) Wise" },
          { title: "For Wise" },
          { title: "Pre-Payment Wise" },
          { title: "Part Payment Wise" },
          { title: "Mortorium Wise" },
          { title: "Cibil Enquiry" },
          { title: "Lockin Period Wise" },
          { title: "Loan TAT Wise" },
          { title: "PF or TDS Deduction Mandatory" },
          { title: "Other" },
        ],
      },
      {
        title: "Business Loan",
        submenu: [
          { title: "Bank Wise" },
          { title: "Applicant Type" },
          { title: "Monthly Salary Wise" },
          { title: "Salary Mode" },
          { title: "Loan Product" },
          { title: "Loan Program" },
          { title: "Loan Amount Wise" },
          { title: "Loan Tenure Wise" },
          { title: "Cibil Score" },
          { title: "Cibil History" },
          { title: "Age Wise" },
          { title: "Employer Type" },
          { title: "Specific Employer Category" },
          { title: "Specific Degree Wise Funding" },
          { title: "Employee Current Job Experience" },
          { title: "Processing Fee Wise" },
          { title: "Foreclosure Charges" },
          { title: "Insurance (%) Wise" },
          { title: "For Wise" },
          { title: "Pre-Payment Wise" },
          { title: "Part Payment Wise" },
          { title: "Mortorium Wise" },
          { title: "Cibil Enquiry" },
          { title: "Lockin Period Wise" },
          { title: "Loan TAT Wise" },
          { title: "PF or TDS Deduction Mandatory" },
          { title: "Other" },
        ],
      },
      {
        title: "Gold Loan",
        submenu: [
          { title: "Bank Wise" },
          { title: "Applicant Type" },
          { title: "Monthly Salary Wise" },
          { title: "Salary Mode" },
          { title: "Loan Product" },
          { title: "Loan Program" },
          { title: "Loan Amount Wise" },
          { title: "Loan Tenure Wise" },
          { title: "Cibil Score" },
          { title: "Cibil History" },
          { title: "Age Wise" },
          { title: "Employer Type" },
          { title: "Specific Employer Category" },
          { title: "Specific Degree Wise Funding" },
          { title: "Employee Current Job Experience" },
          { title: "Processing Fee Wise" },
          { title: "Foreclosure Charges" },
          { title: "Insurance (%) Wise" },
          { title: "For Wise" },
          { title: "Pre-Payment Wise" },
          { title: "Part Payment Wise" },
          { title: "Mortorium Wise" },
          { title: "Cibil Enquiry" },
          { title: "Lockin Period Wise" },
          { title: "Loan TAT Wise" },
          { title: "PF or TDS Deduction Mandatory" },
          { title: "Other" },
        ],
      },
      {
        title: "Education Loan",
        submenu: [
          { title: "Bank Wise" },
          { title: "Applicant Type" },
          { title: "Monthly Salary Wise" },
          { title: "Salary Mode" },
          { title: "Loan Product" },
          { title: "Loan Program" },
          { title: "Loan Amount Wise" },
          { title: "Loan Tenure Wise" },
          { title: "Cibil Score" },
          { title: "Cibil History" },
          { title: "Age Wise" },
          { title: "Employer Type" },
          { title: "Specific Employer Category" },
          { title: "Specific Degree Wise Funding" },
          { title: "Employee Current Job Experience" },
          { title: "Processing Fee Wise" },
          { title: "Foreclosure Charges" },
          { title: "Insurance (%) Wise" },
          { title: "For Wise" },
          { title: "Pre-Payment Wise" },
          { title: "Part Payment Wise" },
          { title: "Mortorium Wise" },
          { title: "Cibil Enquiry" },
          { title: "Lockin Period Wise" },
          { title: "Loan TAT Wise" },
          { title: "PF or TDS Deduction Mandatory" },
          { title: "Other" },
        ],
      },
      {
        title: "New Car Loan",
        submenu: [
          { title: "Bank Wise" },
          { title: "Applicant Type" },
          { title: "Monthly Salary Wise" },
          { title: "Salary Mode" },
          { title: "Loan Product" },
          { title: "Loan Program" },
          { title: "Loan Amount Wise" },
          { title: "Loan Tenure Wise" },
          { title: "Cibil Score" },
          { title: "Cibil History" },
          { title: "Age Wise" },
          { title: "Employer Type" },
          { title: "Specific Employer Category" },
          { title: "Specific Degree Wise Funding" },
          { title: "Employee Current Job Experience" },
          { title: "Processing Fee Wise" },
          { title: "Foreclosure Charges" },
          { title: "Insurance (%) Wise" },
          { title: "For Wise" },
          { title: "Pre-Payment Wise" },
          { title: "Part Payment Wise" },
          { title: "Mortorium Wise" },
          { title: "Cibil Enquiry" },
          { title: "Lockin Period Wise" },
          { title: "Loan TAT Wise" },
          { title: "PF or TDS Deduction Mandatory" },
          { title: "Other" },
        ],
      },
      {
        title: "Used Car Loan",
        submenu: [
          { title: "Bank Wise" },
          { title: "Applicant Type" },
          { title: "Monthly Salary Wise" },
          { title: "Salary Mode" },
          { title: "Loan Product" },
          { title: "Loan Program" },
          { title: "Loan Amount Wise" },
          { title: "Loan Tenure Wise" },
          { title: "Cibil Score" },
          { title: "Cibil History" },
          { title: "Age Wise" },
          { title: "Employer Type" },
          { title: "Specific Employer Category" },
          { title: "Specific Degree Wise Funding" },
          { title: "Employee Current Job Experience" },
          { title: "Processing Fee Wise" },
          { title: "Foreclosure Charges" },
          { title: "Insurance (%) Wise" },
          { title: "For Wise" },
          { title: "Pre-Payment Wise" },
          { title: "Part Payment Wise" },
          { title: "Mortorium Wise" },
          { title: "Cibil Enquiry" },
          { title: "Lockin Period Wise" },
          { title: "Loan TAT Wise" },
          { title: "PF or TDS Deduction Mandatory" },
          { title: "Other" },
        ],
      },
      {
        title: "Health Care Equipment Loan",
        submenu: [
          { title: "Bank Wise" },
          { title: "Applicant Type" },
          { title: "Monthly Salary Wise" },
          { title: "Salary Mode" },
          { title: "Loan Product" },
          { title: "Loan Program" },
          { title: "Loan Amount Wise" },
          { title: "Loan Tenure Wise" },
          { title: "Cibil Score" },
          { title: "Cibil History" },
          { title: "Age Wise" },
          { title: "Employer Type" },
          { title: "Specific Employer Category" },
          { title: "Specific Degree Wise Funding" },
          { title: "Employee Current Job Experience" },
          { title: "Processing Fee Wise" },
          { title: "Foreclosure Charges" },
          { title: "Insurance (%) Wise" },
          { title: "For Wise" },
          { title: "Pre-Payment Wise" },
          { title: "Part Payment Wise" },
          { title: "Mortorium Wise" },
          { title: "Cibil Enquiry" },
          { title: "Lockin Period Wise" },
          { title: "Loan TAT Wise" },
          { title: "PF or TDS Deduction Mandatory" },
          { title: "Other" },
        ],
      },
      {
        title: "Passenger Commercial Vehicle",
        submenu: [
          { title: "Bank Wise" },
          { title: "Applicant Type" },
          { title: "Monthly Salary Wise" },
          { title: "Salary Mode" },
          { title: "Loan Product" },
          { title: "Loan Program" },
          { title: "Loan Amount Wise" },
          { title: "Loan Tenure Wise" },
          { title: "Cibil Score" },
          { title: "Cibil History" },
          { title: "Age Wise" },
          { title: "Employer Type" },
          { title: "Specific Employer Category" },
          { title: "Specific Degree Wise Funding" },
          { title: "Employee Current Job Experience" },
          { title: "Processing Fee Wise" },
          { title: "Foreclosure Charges" },
          { title: "Insurance (%) Wise" },
          { title: "For Wise" },
          { title: "Pre-Payment Wise" },
          { title: "Part Payment Wise" },
          { title: "Mortorium Wise" },
          { title: "Cibil Enquiry" },
          { title: "Lockin Period Wise" },
          { title: "Loan TAT Wise" },
          { title: "PF or TDS Deduction Mandatory" },
          { title: "Other" },
        ],
      },
      {
        title: "CGTMISE",
        submenu: [
          { title: "Bank Wise" },
          { title: "Applicant Type" },
          { title: "Monthly Salary Wise" },
          { title: "Salary Mode" },
          { title: "Loan Product" },
          { title: "Loan Program" },
          { title: "Loan Amount Wise" },
          { title: "Loan Tenure Wise" },
          { title: "Cibil Score" },
          { title: "Cibil History" },
          { title: "Age Wise" },
          { title: "Employer Type" },
          { title: "Specific Employer Category" },
          { title: "Specific Degree Wise Funding" },
          { title: "Employee Current Job Experience" },
          { title: "Processing Fee Wise" },
          { title: "Foreclosure Charges" },
          { title: "Insurance (%) Wise" },
          { title: "For Wise" },
          { title: "Pre-Payment Wise" },
          { title: "Part Payment Wise" },
          { title: "Mortorium Wise" },
          { title: "Cibil Enquiry" },
          { title: "Lockin Period Wise" },
          { title: "Loan TAT Wise" },
          { title: "PF or TDS Deduction Mandatory" },
          { title: "Other" },
        ],
      },
      {
        title: "Loan Against Security",
        submenu: [
          { title: "Bank Wise" },
          
          { title: "Applicant Type" },
          { title: "Monthly Salary Wise" },
          { title: "Salary Mode" },
          { title: "Loan Product" },
          { title: "Loan Program" },
          { title: "Loan Amount Wise" },
          { title: "Loan Tenure Wise" },
          { title: "Cibil Score" },
          { title: "Cibil History" },
          { title: "Age Wise" },
          { title: "Employer Type" },
          { title: "Specific Employer Category" },
          { title: "Specific Degree Wise Funding" },
          { title: "Employee Current Job Experience" },
          { title: "Processing Fee Wise" },
          { title: "Foreclosure Charges" },
          { title: "Insurance (%) Wise" },
          { title: "For Wise" },
          { title: "Pre-Payment Wise" },
          { title: "Part Payment Wise" },
          { title: "Mortorium Wise" },
          { title: "Cibil Enquiry" },
          { title: "Lockin Period Wise" },
          { title: "Loan TAT Wise" },
          { title: "PF or TDS Deduction Mandatory" },
          { title: "Other" },
        ],
      },
      {
        title: "Working Capital OD Limit",
        submenu: [
          { title: "Bank Wise" },
          { title: "Applicant Type" },
          { title: "Monthly Salary Wise" },
          { title: "Salary Mode" },
          { title: "Loan Product" },
          { title: "Loan Program" },
          { title: "Loan Amount Wise" },
          { title: "Loan Tenure Wise" },
          { title: "Cibil Score" },
          { title: "Cibil History" },
          { title: "Age Wise" },
          { title: "Employer Type" },
          { title: "Specific Employer Category" },
          { title: "Specific Degree Wise Funding" },
          { title: "Employee Current Job Experience" },
          { title: "Processing Fee Wise" },
          { title: "Foreclosure Charges" },
          { title: "Insurance (%) Wise" },
          { title: "For Wise" },
          { title: "Pre-Payment Wise" },
          { title: "Part Payment Wise" },
          { title: "Mortorium Wise" },
          { title: "Cibil Enquiry" },
          { title: "Lockin Period Wise" },
          { title: "Loan TAT Wise" },
          { title: "PF or TDS Deduction Mandatory" },
          { title: "Other" },
        ],
      },
    ],
  },


  {
    title: "Cards",
    
  },
  {
    title: "Insurance",
  },
  {
    title: "Cybil Score",
  },
  {
    title: "EMI Calculator",
  },
];


